/*
  @author Sven Wisotzky
  
  © 2026 Nokia
  Licensed under the BSD 3-Clause License
  SPDX-License-Identifier: BSD-3-Clause

  Builds the HTML for the XML Navigator webview by inlining CSS.
  CSS is embedded at build time (scripts/embed-webview-css.js) so it works when
  the extension is packaged (.vscodeignore excludes src/).
*/

import * as vscode from 'vscode';
import { strings } from '../webview/strings';

function getEmbeddedCss(): string {
  try {
    // Build-time embedded CSS; require is used because the file is generated by scripts/embed-webview-css.js
    // eslint-disable-next-line @typescript-eslint/no-require-imports, @typescript-eslint/no-var-requires
    return (require('../webviewCss.embed.js') as string) || '';
  } catch {
    return '';
  }
}

/**
 * Returns the full HTML document for the webview panel.
 * Codicon font URI is injected into a small inline style block so the font loads in the webview.
 */
export function getHtmlForWebview(
  webview: vscode.Webview,
  scriptUri: vscode.Uri,
  codiconsCssUri: vscode.Uri,
  codiconsFontUri: vscode.Uri
): string {
  const codiconFontFace = `
    @font-face {
      font-family: "codicon";
      font-display: block;
      src: url("${codiconsFontUri}") format("truetype");
    }
  `;
  const mainCss = getEmbeddedCss();

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>${strings.appTitle}</title>
  <link rel="stylesheet" href="${codiconsCssUri}" />
  <style>
${codiconFontFace}
${mainCss}
  </style>
</head>
<body>
  <div id="path-bar">
    <div id="path-chips"></div>
    <div id="path-input-wrap">
      <span id="path-input-ghost" aria-hidden="true"></span>
      <input id="path-input" type="text" placeholder="${strings.placeholderPathInput}" title="" autocomplete="off" />
    </div>
    <span id="copy-path-btn" role="button" tabindex="0" title="${strings.tooltipCopyPath}" aria-label="${strings.tooltipCopyPath}">
      <svg class="copy-icon" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M3 5V12.73C2.4 12.38 2 11.74 2 11V5C2 2.79 3.79 1 6 1H9C9.74 1 10.38 1.4 10.73 2H6C4.35 2 3 3.35 3 5ZM11 15H6C4.897 15 4 14.103 4 13V5C4 3.897 4.897 3 6 3H11C12.103 3 13 3.897 13 5V13C13 14.103 12.103 15 11 15ZM12 5C12 4.448 11.552 4 11 4H6C5.448 4 5 4.448 5 5V13C5 13.552 5.448 14 6 14H11C11.552 14 12 13.552 12 13V5Z"/></svg>
      <svg class="check-icon" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M13.6572 3.13573C13.8583 2.9465 14.175 2.95614 14.3643 3.15722C14.5535 3.35831 14.5438 3.675 14.3428 3.86425L5.84277 11.8642C5.64597 12.0494 5.33756 12.0446 5.14648 11.8535L1.64648 8.35351C1.45121 8.15824 1.45121 7.84174 1.64648 7.64647C1.84174 7.45121 2.15825 7.45121 2.35351 7.64647L5.50976 10.8027L13.6572 3.13573Z"/></svg>
    </span>
  </div>
  <div id="context-menu" style="display: none; position: fixed; z-index: 200; background: var(--vscode-menu-background); border: 1px solid var(--vscode-menu-border); box-shadow: 0 2px 8px rgba(0,0,0,0.2); padding: 4px 0; min-width: 160px;"></div>
  <div id="list-view" tabindex="-1">
    <div id="list-view-placeholder">${strings.placeholderLoading}</div>
  </div>
  <div id="table-row-count" style="display: none;"></div>
  <div id="status-bar" style="flex-shrink: 0; padding: 4px 8px; font-size: 12px; color: var(--vscode-descriptionForeground); background: var(--vscode-editor-background); border-top: 1px solid var(--vscode-panel-border);"><span class="status-filename" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap; min-width: 0;"></span><span class="status-count" style="flex-shrink: 0;"></span></div>
  <script src="${scriptUri}"></script>
</body>
</html>`;
}
